# Generated by Django 2.1.7 on 2019-04-24 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(auto_now_add=True)),
                ('months_of_rent', models.IntegerField()),
                ('real_rental_per_month', models.IntegerField()),
                ('commission_rate', models.FloatField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoqu', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('house_type', models.CharField(max_length=100)),
                ('rental_per_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('real_price', models.IntegerField()),
                ('commission_rate', models.FloatField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoqu', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('house_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salecontract',
            name='sale_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.SaleInfo'),
        ),
        migrations.AddField(
            model_name='salecontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salecommission',
            name='sale_contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.SaleContract'),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='rent_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.RentInfo'),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentcommission',
            name='rent_contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.RentContract'),
        ),
    ]
